### ISSUE TITLE
Remediation cost for the next grade seems to be missing from API

### ISSUE THREAD

**Issue by mickaelandrieu** [symfonycorp/insight#50]
Hi,

I have found a little issue on insight cli which always say I need only 0 hour of remediation cost to reach the next grade.

After investigation, I have checked the xml returned for my analyzes and I don't saw any `remediation-cost-for-next-grade` as expected by JMS serializer for an Analysis object.

Did I misunderstood something or do you need to update the XML returned ?

(for instance, you can take a look to https://insight.sensiolabs.com/api/projects/8e55fbb8-0902-4666-8459-ed5662e220c3/analyses/64)

Regards,

**Comment by lyrixx** [comment]
ping @deguif

**Comment by deguif** [comment]
I will have a look.

**Comment by mickaelandrieu** [comment]
@deguif thanks :)
