### ISSUE TITLE
Not compatible with Symfony 3.0

### ISSUE THREAD

**Issue by romaricdrigon** [symfonycorp/insight#52]
Hello,

Right now we have those 2 requirements:

``` json
"symfony/console": "~2.3",
"symfony/expression-language": "~2.4"
```

Those prevent Insight SDK to be used in any Symfony 3.0 project. Could you please loosen those?

Thanks

**Comment by GrahamCampbell** [comment]
The dependency on guzzle 3 is going to be a blocker anyway, since it depends on symfony 2 too.

**Comment by lyrixx** [comment]
Could one of you open a PR?

**Comment by stof** [comment]
@lyrixx how would you handle the guzzle 3 dependency ? Migrating away from it requires a BC break (as the first 2 parameters of the Api class are the guzzle options and an optional guzzle client).

And guzzle 3 won't be updated to depend on ``symfony/event-dispatcher ~2.1 || ~3.0`` (even though no change is required as this component is BC), as it is unmaintained since years

**Comment by GrahamCampbell** [comment]
@stof I think this package should just break BC and move to only guzzle 5/6, in a new major release.

**Comment by lyrixx** [comment]
I'm fine to break the BC and to bump a major version. 

And I would be happier to have this project without any deps to guzzle. For the [Player](github.com/blackfireio/player) we do lot's of API call, but do not depends on guzzle. And IMHO it's the best way to deal with guzzle / http client for this kind of project.

**Comment by stof** [comment]
> For the Player we do lot's of API call, but do not depends on guzzle

That's wrong. the Player depends on Guzzle 6

**Comment by stof** [comment]
btw, your link to the player is broken (missing ``https://``)

**Comment by lyrixx** [comment]
> That's wrong. the Player depends on Guzzle 6

oh ... I did not know that. but anyway depending on guzzle for 3rd party lib is boring...

**Comment by stof** [comment]
@lyrixx my suggestion is to switch to HTTPlug

**Comment by fbourigault** [comment]
As an active HTTPlug contributor, I agree with switching to it. Sadly it will require a new major release. You may be forced also to split out the CLI tool as the cli-tool will require you to choose a php-http/client-implementation.
You can join the [Slack channel](http://slack.httplug.io/) to talk about this.

**Comment by lyrixx** [comment]
Thanks for this feedback. But I don't get why we need to split this repo.

**Comment by stof** [comment]
@lyrixx the CLI needs to select a HTTPlug implementation embedded in the phar. the SDK should not force a choice (otherwise, you have to use an implementation which is *not* a Guzzle one, to avoid the same issues about incompatibility with other Guzzle versions for instance, etc...)

**Comment by fbourigault** [comment]
Can be part of the #42 :)

**Comment by GrahamCampbell** [comment]
Is this issue still relevant? This package no longer depends on Guzzle 3.

**Comment by GrahamCampbell** [comment]
That is, I think we can close this now?

**Comment by stof** [comment]
@GrahamCampbell you can close this one... and open a new one about the support for Symfony 5 :smile:

**Comment by romaricdrigon** [comment]
Indeed, it is not relevant anymore. And +1 for Symfony 5 support!
