### ISSUE TITLE
What is the best way to do i18n links?

### ISSUE THREAD

**Issue by arodiss** [symfonycorp/insight#68]
Sorry for reporting this in the wrong place - this should go to `Insight itself`, not to SDK, but I don't know where to report such a thing.

My question is how should I do links within translatable text? Now I am doing something like
```
{{ 'Look %s here %s for more information'
  | trans
  | format('<a href="' ~ path("MyRoute") ~ '">', '</a>')
  | raw
}}
```
but for this Insight shows critical error "potential XSS vulnerability"
I don't want to disable XSS check as a whole and don't want to see this error - so is there a way to do this?

**Comment by lyrixx** [comment]
Why don't you do:

```jinja
<a href="{{ path('my route') }}">
    {{ 'Look %s here %s for more information'|trans }}
</a>
```
 ?
