### ISSUE TITLE
Error returned if no --fail-condition filled or --no-wait arg filled

### ISSUE THREAD

**Issue by paydaycay** [symfonycorp/insight#96]
Hi,

Since the v1.7.2 is deployed (today ?), our CI is returning an error in the Insights job. We must make this step non-blocking fro now but we don't want it.

The problem seems to be in #94 where you replaced `return;` by `return 1;` in Commands.

Could you fix this ASAP with a rebuild please or tell us why now it returns as an error ? 

Regards.

**Comment by tgalopin** [comment]
This is indeed a bug, fixing it!
